### ISSUE TITLE
Not working with doctrine/orm 3.0 and doctrine/lexer 3.0

### ISSUE THREAD

**Issue by Wimble84** [ScientaNL/DoctrineJsonFunctions#104]
Hi !

Symfony: 7.0.3
Doctrine ORM: 3.0
Doctrine Lexer: 3.0

When trying to use JSON_GET_TEXT on postgres DB like this

```php
public function findAllByRoles(string $role): array 
{
        $qb = $this->createQueryBuilder('u');
        $qb
            ->where("JSON_GET_TEXT(u.roles, 0) = :role")
            ->setParameter('role', $role)
            ->orderBy('u.lastname', 'ASC')
            ->addOrderBy('u.firstname', 'ASC');

        return $qb->getQuery()->getResult();
}
```

I get this error
Undefined constant Doctrine\ORM\Query\Lexer::T_IDENTIFIER

Before doctrine/orm and doctrine/lexer 3.0, tokens are stored directly as constants. But now (in 3.0) tokens are stored in TokenType Enum

**Comment by Hikariii** [comment]
Release [5.5.0](https://github.com/ScientaNL/DoctrineJsonFunctions/releases/tag/5.5.0) supports orm 3
