### ISSUE TITLE
JSON_EXTRACT missing in MariaDB

### ISSUE THREAD

**Issue by igoooor** [ScientaNL/DoctrineJsonFunctions#116]
I can use JSON_EXTRACT in MariaDB, but the package here does not seem to support it since I updated to symfony 7 & doctrine/dbal 4

I'm not sure what additional information I could provide to help debug that. But also on the README of the project, JSON_EXTRACT is not listed in the MariaDB column.

**Comment by igoooor** [comment]
I think some others might be missing, I could find a lot in https://mariadb.com/kb/en/json-functions/

**Comment by igoooor** [comment]
Sorry if I was not clear in my initial message, but that's what I mean, it does not work with my setup, it gives me the following error: `Operation "JSON_EXTRACT" is not supported by platform.`
Here are some more info on my setup:
- I am using mariadb 10.8 as database
- `DATABASE_URL=mysql://symfony:symfony@local-db:3306/symfony?serverVersion=10.8.5-MariaDB`
- my doctrine packages:
```
"doctrine/annotations": "^2.0", # 2.0.1
"doctrine/doctrine-bundle": "^2.2", # 2.12.0
"doctrine/doctrine-migrations-bundle": "^3.0", # 3.3.1
"doctrine/orm": "3.*", 3.2.0
```
Which are all up to date with latest version.
Let me know if I can provide more info. Thanks

**Comment by victor-prdh** [comment]
Hey, sorry for the delay.

I created this small test: https://github.com/victor-prdh/test-maria.

It's working well for me. Do you have a small reproducer by any chance?

**Comment by Lustmored** [comment]
Just as a note, I have created PR that should solve the issue. If you could test and review the PR it would surely help :panda_face:

**Comment by rmikalkenas** [comment]
seems that none of functions work with MariaDB and doctrine dbal v4.
Can confirm, that @Lustmored PR fixes and makes it work again :rocket:
