### ISSUE TITLE
Add support for new MariaDB JSON functions

### ISSUE THREAD

**Issue by dieisraels** [ScientaNL/DoctrineJsonFunctions#28]
Since MariaDB 10.2.3 there are more JSON functions:
https://mariadb.com/kb/en/library/json-functions/

**Comment by Hikariii** [comment]
We renamed the Syslogic organisation name to Scienta.
The github repository name was already updated.
The composer namespace is updated recently.
This now also includes a change of the root namespace from Syslogic\ to Scienta\.
The rename work is published in a new 4.0 version on packagist:
https://packagist.org/packages/scienta/doctrine-json-functions

**Comment by Hikariii** [comment]
New mariadb functions can be added in the new master branch for version 4.0
These can also be verified and tested with phpunit.

**Comment by Hikariii** [comment]
Fixed in 5.1.0
