### ISSUE TITLE
JSON_QUOTE doesn't accept a placeholder

### ISSUE THREAD

**Issue by bpolaszek** [ScientaNL/DoctrineJsonFunctions#39]
Hello there,

When doing a prepared DQL statement containing this:

```sql
JSON_QUOTE(:foo)
```

Then binding `:foo` to a scalar value, here's the error I get:

> [Syntax Error] line 0, col 93: Error: Expected string, got ':foo'

I can solve this by changing this code:
```php
# src/Query/AST/Functions/Mysql/JsonQuote.php

class JsonQuote extends MysqlJsonFunctionNode
{
    const FUNCTION_NAME = 'JSON_QUOTE';

    /** @var string[] */
    protected $requiredArgumentTypes = [self::STRING_ARG];
}
```

To this one:
```php
# src/Query/AST/Functions/Mysql/JsonQuote.php

class JsonQuote extends MysqlJsonFunctionNode
{
    const FUNCTION_NAME = 'JSON_QUOTE';

    /** @var string[] */
    protected $requiredArgumentTypes = [self::VALUE_ARG];
}
```

But would there be any drawbacks of doing this?

Tested platform: MySQL 5.7.

Thank you,
Ben

**Comment by Hikariii** [comment]
I think your solution is correct.
If all the tests succeed after changing this then please submit a PR

**Comment by bpolaszek** [comment]
They do :-)

PR on the way!
