### ISSUE TITLE
Allow double quotes in all functions

### ISSUE THREAD

**Issue by apfelbox** [ScientaNL/DoctrineJsonFunctions#41]
Hi 👋 

As it turns out, all functions currently support this:

```dql
JSON_EXTRACT(my_field, '$.prop')
```

but do not accept this:
```dql
JSON_EXTRACT(my_field, "$.prop")
```

This fails with a parse error:

```
Doctrine\ORM\Query\QueryException: [Syntax Error] line 0, col 64: Error: Expected StateFieldPathExpression | string | InputParameter | FunctionsReturningStrings | AggregateExpression, got '"'
```

In SQL both is perfectly valid and it feels weird, that this makes a difference here.
Is this an issue in doctrine or in this library?

Thanks for your great work!

**Comment by Hikariii** [comment]
This is a DQL issue and not related to json functions https://github.com/doctrine/orm/issues/5613.
I also added an extra test to confirm double quotes nor working: https://github.com/ScientaNL/DoctrineJsonFunctions/blob/master/tests/Query/Functions/Mysql/JsonExctractTest.php#L18-L28
