### ISSUE TITLE
JSON_EXTRACT for LEFT JOIN

### ISSUE THREAD

**Issue by dwatson251** [ScientaNL/DoctrineJsonFunctions#47]
Hi,

I am using a property on the JSON document as a foreign key, utilising the JSON_EXTRACT function as part of a LEFT JOIN,

When doctrine (2.4.8) comes to hydrate the objects, it requires a "parentAliasMap" in order to merge the joined result on to the entity. (Doctrine\ORM\Internal\Hydration\ObjectHydrator.php:393)

Is it possible to define a relationship on an entity class this way? (Or at least trick Doctrine in to dynamically creating the relationship on the entity result.

Please let me know if this question needs any clarification. I look forward to your response.

Thank you,

Daniel

**Comment by Hikariii** [comment]
I'd have to make some time to dive into this.
Is it maybe a possibility to use mysql to extract the json value and create a virtual property.
This can then be referenced when using your entity.
You do need a somewhat complex event listener to remove the field from the metadata when writing to the db and mapping it when selecting from the db

**Comment by Hikariii** [comment]
You could check https://github.com/ScientaNL/DoctrineJsonFunctions/issues/45 on how to go about something like that.

**Comment by dwatson251** [comment]
Thanks for your reply - This is very much the approach I have gone for. I created a MappedSuperClass that extended the target entity and limited to "read-only" doctrine DQL methods to extract the property (via a generated column) I needed.

It's not a perfect solution and I really hope you consider a solid solution. As I understand at the time of writing, their are Custom hydrators in Doctrine which I haven't had chance to explore, but they may hold the solution.
