### ISSUE TITLE
Thoughts on support for SQLite?

### ISSUE THREAD

**Issue by bobdenotter** [ScientaNL/DoctrineJsonFunctions#49]
Hi, 

For [our project](https://github.com/bolt/core/), we could really use this library, but (basic) SQLite support is a hard requirement for our userbase. 

I've done some preliminary testing, and it seems that at least `JSON_EXTRACT` will work on sqlite as well. Is SQLite support for this package overall something to be considered?

**Comment by hermzz** [comment]
Agreed, I'd assume all the methods described here: https://www.sqlite.org/json1.html are supported by the current PDO SQLITE library.

**Comment by skroczek** [comment]
I would love to see this merged :heart: I just installed it and it works like a charm. Thanks @hermzz

**Comment by Hikariii** [comment]
Merged and released in 4.1.* https://packagist.org/packages/scienta/doctrine-json-functions
