### ISSUE TITLE
JsonB operators missing?

### ISSUE THREAD

**Issue by KDederichs** [ScientaNL/DoctrineJsonFunctions#64]
Hey,
I'm looking for the ? operator for jsonb (Does the key/element string exist within the JSON value) but it doesn't seem to be included.

Any reason why it might be missing?

https://www.postgresql.org/docs/9.4/functions-json.html

**Comment by Hikariii** [comment]
It looks like you're right.
The reason it is missing is because nobody added it yet.
You're welcome to added (with proper tests).

**Comment by KDederichs** [comment]
@Hikariii 
Hmm I looked at it a bit closer and I think I might know why it's missing:

since ? seems to be used for substition of parameters in the DQL that operator gets treated as parameter substitution...

Do you by chance know if it's possible to suppress that?

**Comment by KDederichs** [comment]
Ok after digging even deeper it seems that `JSONB_EXISTS` is an alias for ? and `JSONB_EXISTS` is implemented
