### ISSUE TITLE
Add DBAL for (some) json functions

### ISSUE THREAD

**Issue by c33s** [ScientaNL/DoctrineJsonFunctions#65]
it would really make a great DX (developer experience) if we would have some kind of DBAL for all this different json functions. this would be awesome.

it can happen that test databases are sqlite but staging and production are postgresql.

i made an ugly hack to achieved this https://gist.github.com/c33s/979564811ce611a47f5d157d0d62528a but i would love to see such functions integrated in this package.

**Comment by Hikariii** [comment]
To me it seems wanting to use the same queries for two different platforms is a different problem that what this repository tries to solve.
I think a new project could be started, using this repo to create an abstraction on top of these functions.
You could then declare functions that are usable across different platforms and implement the platform-specific functions from this repository.

Such an undertaking would be out of scope for this repository though.
Also, using different databases within your DTAP environments is bad practice imho.
