### ISSUE TITLE
JSON_OVERLAPS

### ISSUE THREAD

**Issue by YoukeZhang** [ScientaNL/DoctrineJsonFunctions#70]
Can you add JSON_OVERLAPS function
[https://dev.mysql.com/doc/refman/8.0/en/json-search-functions.html#function_json-overlaps](url)

**Comment by Hikariii** [comment]
Added in 4.4.0: 
- https://github.com/ScientaNL/DoctrineJsonFunctions/pull/71
- https://github.com/ScientaNL/DoctrineJsonFunctions/releases/tag/4.4.0
