### ISSUE TITLE
JSON_SEARCH missing for mariadb

### ISSUE THREAD

**Issue by SalvatorePollaci** [ScientaNL/DoctrineJsonFunctions#86]
Hi,
it seems that JSON_SEARCH function is not supported by this library even though mariadb supports it (https://mariadb.com/kb/en/json_search/).

Could such function be supported by this library?

Thanks

**Comment by Hikariii** [comment]
Almost all the mysql functions are shared between mysql and mariadb, except for (atm json_value). The syntax in the docs look the same, so `Scienta\DoctrineJsonFunctions\Query\AST\Functions\Mysql\JsonSearch` should be usable with mariadb also.
